version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: learnsphere-mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: learnsphere-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/learnsphere_db

  client:
    build: ./client
    container_name: learnsphere-client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000

